[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "freetype",
  "freetype-dev",
  "harfbuzz",
  "ca-certificates",
  "ttf-freefont",
  "nodejs_18",
  "yarn"
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"
